package Constants;

public class ConstantsQrCode {
    public static String QRCODE_NOT_FOUND = "MDAwMjAxMjYzMzAwMTRCUi5HT1YuQkNCLlBJWDAxMTE3MDMyNjE2NTY5MDUyMDQwMDAwNTMwMzk4NjU0MDU1MC4wMDU4MDJCUjU5MTFCdWlsZGVycyAwMTYwMDJTUDYyMTUwNTEyUEFHQU1FTlRPMDE2MzA0NDMxMg==";
    public static String QRCODE_VALID_10 = "MDAwMjAxMjYzMzAwMTRCUi5HT1YuQkNCLlBJWDAxMTE3MDMyNjE2NTY5MDUyMDQwMDAwNTMwMzk4NjU0MDUxMC4wMDU4MDJCUjU5MTFCdWlsZGVycyAwMTYwMDJTUDYyMTUwNTExUEFHQU1FTlRPMDE2MzA0NDMxMg==";
    public static String QRCODE_VALID_20 = "MDAwMjAxMjYzMzAwMTRCUi5HT1YuQkNCLlBJWDAxMTE3MDMyNjE2NTY5MDUyMDQwMDAwNTMwMzk4NjU0MDUyMC4wMDU4MDJCUjU5MTFCdWlsZGVycyAwMTYwMDJTUDYyMTUwNTExUEFHQU1FTlRPMDE2MzA0NDMxMg==";
    public static String QRCODE_VALID_50 = "MDAwMjAxMjYzMzAwMTRCUi5HT1YuQkNCLlBJWDAxMTE3MDMyNjE2NTY5MDUyMDQwMDAwNTMwMzk4NjU0MDU1MC4wMDU4MDJCUjU5MTFCdWlsZGVycyAwMTYwMDJTUDYyMTUwNTExUEFHQU1FTlRPMDE2MzA0NDMxMg==";
    public static String QRCODE_EMPTY = "";
    public static String QRCODE_INVALID = "A";
}
